package log

import (
	"encoding/json"
	CorporatePurchase "github.com/starkbank/sdk-go/starkbank/corporatepurchase"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	CorporatePurchase.Log struct
//
//	Every time a CorporatePurchase entity is updated, a corresponding CorporatePurchase.Log
//	is generated for the entity. This log is never generated by the
//	user.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Purchase [CorporatePurchase struct]: CorporatePurchase entity to which the log refers to.
//	- CorporateTransactionId [string]: Transaction ID related to the CorporateCard.
//	- Description [string]: purchase descriptions. ex: "my_description"
//	- Errors [slice of strings]: Slice of errors linked to this CorporatePurchase event
//	- Type [string]: Type of the CorporatePurchase event which triggered the log creation. ex: "approved", "canceled", "confirmed", "denied", "reversed", "voided".
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id                     string                              `json:",omitempty"`
	Purchase               CorporatePurchase.CorporatePurchase `json:",omitempty"`
	CorporateTransactionId string                              `json:",omitempty"`
	Description            string                              `json:",omitempty"`
	Errors                 []map[string]interface{}            `json:",omitempty"`
	Type                   string                              `json:",omitempty"`
	Created                *time.Time                          `json:",omitempty"`
}

var Object Log
var objects []Log
var resource = map[string]string{"name": "CorporatePurchaseLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific CorporatePurchase.Log by its id
	//
	//	Receive a single CorporatePurchase.Log struct previously created by the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- corporatePurchase.Log struct that corresponds to the given id.
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &Object)
	if unmarshalError != nil {
		return Object, err
	}
	return Object, err
}

func Query(params map[string]interface{}, user user.User) chan Log {
	//	Retrieve CorporatePurchase.Log structs
	//
	//	Receive a channel of CorporatePurchase.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"approved", "canceled", "confirmed", "denied", "reversed", "voided"}
	//		- purchaseIds [slice of strings, default nil]: Slice of Purchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- ids [slice of strings, default nil]: Slice of CorporatePurchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- channel of CorporatePurchase.Log structs with updated attributes
	logs := make(chan Log)
	query := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &Object)
			if err != nil {
				print(err.Error())
			}
			logs <- Object
		}
		close(logs)
	}()
	return logs
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged CorporatePurchase.Log structs
	//
	//	Receive a slice of up to 100 CorporatePurchase.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. Max = 100. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date.  ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date.  ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"approved", "canceled", "confirmed", "denied", "reversed", "voided"}
	//		- purchaseIds [slice of strings, default nil]: Slice of Purchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- ids [slice of strings, default nil]: Slice of CorporatePurchase ids to filter logs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- slice of CorporatePurchase.Log structs with updated attributes
	//	- cursor to retrieve the next page of CorporatePurchase.Log structs
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &objects)
	if unmarshalError != nil {
		return objects, cursor, err
	}
	return objects, cursor, err
}
