package log

import (
	"encoding/json"
	SplitProfile "github.com/starkbank/sdk-go/starkbank/splitprofile"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	SplitProfile.Log struct
//
//	Every time a SplitProfile entity is modified, a corresponding SplitProfile.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the SplitProfile.
//
//	Attributes (return-only):
//	- Id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- Profile [SplitProfile struct]: SplitProfile entity to which the log refers to.
//	- Errors [slice of strings]: slice of errors linked to this SplitProfile event.
//	- Type [string]: type of the SplitProfile event which triggered the log creation. ex: "created" or "updated"
//	- Created [time.Time]: creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC)

type Log struct {
	Id      string                    `json:",omitempty"`
	Profile SplitProfile.SplitProfile `json:",omitempty"`
	Errors  []string                  `json:",omitempty"`
	Type    string                    `json:",omitempty"`
	Created *time.Time                `json:",omitempty"`
}

var resource = map[string]string{"name": "SplitProfileLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific SplitProfile.Log by its id
	//
	//	Receive a single SplitProfile.Log struct previously created by the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- SplitProfile.Log struct that corresponds to the given id.
	var splitProfileLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &splitProfileLog)
	if unmarshalError != nil {
		return splitProfileLog, err
	}
	return splitProfileLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve SplitProfile.Log structs
	//
	//	Receive a channel of SplitProfile.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: date filter for objects created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for objects created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved objects by event types. ex: []string{"created", "updated"}
	//		- profileIds [slice of strings, default nil]: slice of SplitProfile ids to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- channel of SplitProfile.Log structs with updated attributes
	var splitProfileLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &splitProfileLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- splitProfileLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logsError)
		close(logs)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged SplitProfile.Log structs
	//
	//	Receive a slice of up to 100 SplitProfile.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: cursor returned on the previous page function call
	//		- limit [int, default 100]: maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: date filter for objects created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for objects created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved objects by event types. ex: []string{"created", "updated"}
	//		- profileIds [slice of strings, default nil]: slice of SplitProfile ids to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- slice of SplitProfile.Log structs with updated attributes
	//	- cursor to retrieve the next page of SplitProfile.Log structs
	var splitProfileLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &splitProfileLogs)
	if unmarshalError != nil {
		return splitProfileLogs, cursor, err
	}
	return splitProfileLogs, cursor, err
}
