package split

import (
	"encoding/json"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	Split struct
//
//	When you initialize a Split, the entity will not be automatically
//	created in the Stark Bank API. The 'create' function sends the objects
//	to the Stark Bank API and returns the list of created objects.
//
//	Parameters (required):
//	- Amount [int]: Value to send to receivers. ex: 1000 (= R$ 10.00)
//	- ReceiverId [string]: Split receiver unique id. ex: "5656565656565656"
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when split is created. ex: "5656565656565656"
//	- Source [string]: Source receivable which generated this split object. ex: "5656565656565656"
//	- ExternalId [string]: Unique id, generated by the system, to avoid duplicated splits. ex: "invoice/1234/receiver/5678"
//	- Tags [slice of strings]: Slice of strings for tagging. ex: []string{"tony", "stark"}
//	- Scheduled [time.Time]: Payment scheduled date or datetime. ex: time.Date(2020, 3, 10, 15, 17, 3, 0, time.UTC)
//	- Status [string]: Current payment status. ex: "success" or "failed"
//	- Created [time.Time]: Creation datetime for the payment. ex: time.Date(2020, 3, 10, 10, 30, 0, 0, time.UTC)
//	- Updated [time.Time]: Update datetime for the payment. ex: time.Date(2020, 3, 10, 10, 30, 0, 0, time.UTC)

type Split struct {
	Amount     int        `json:",omitempty"`
	ReceiverId string     `json:",omitempty"`
	Id         string     `json:",omitempty"`
	Source     string     `json:",omitempty"`
	ExternalId string     `json:",omitempty"`
	Tags       []string   `json:",omitempty"`
	Scheduled  *time.Time `json:",omitempty"`
	Status     string     `json:",omitempty"`
	Created    *time.Time `json:",omitempty"`
	Updated    *time.Time `json:",omitempty"`
}

var resource = map[string]string{"name": "Split"}

func Get(id string, user user.User) (Split, Error.StarkErrors) {
	//	Retrieve a specific Split by its id
	//
	//	Receive a single Split struct from the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Split struct that corresponds to the given id
	var split Split
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &split)
	if unmarshalError != nil {
		return split, err
	}
	return split, err
}

func Query(params map[string]interface{}, user user.User) (chan Split, chan Error.StarkErrors) {
	//	Retrieve Split structs
	//
	//	Receive a channel of Split structs from the Stark Bank API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- tags [slice of strings, default nil]: Tags to filter retrieved structs. ex: []string{"tony", "stark"}
	//		- ids [slice of strings, default nil]: List of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- receiverIds [slice of strings, default nil]: List of receiver ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- status [string, default nil]: Filter for status of retrieved structs. ex: "success"
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Channel of Split structs with updated attributes
	var split Split
	splits := make(chan Split)
	splitsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &split)
			if err != nil {
				splitsError <- Error.UnknownError(err.Error())
				continue
			}
			splits <- split
		}
		for err := range errorChannel {
			splitsError <- err
		}
		close(splits)
		close(splitsError)
	}()
	return splits, splitsError
}

func Page(params map[string]interface{}, user user.User) ([]Split, string, Error.StarkErrors) {
	//	Retrieve paged Split structs
	//
	//	Receive a slice of up to 100 Split structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- tags [slice of strings, default nil]: Tags to filter retrieved structs. ex: []string{"tony", "stark"}
	//		- ids [slice of strings, default nil]: List of ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- receiverIds [slice of strings, default nil]: List of receiver ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//		- status [string, default nil]: Filter for status of retrieved structs. ex: "success"
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Slice of Split structs with updated attributes
	//	- Cursor to retrieve the next page of Split structs
	var splits []Split
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &splits)
	if unmarshalError != nil {
		return splits, cursor, err
	}
	return splits, cursor, err
}
