package log

import (
	"encoding/json"
	Transfer "github.com/starkbank/sdk-go/starkbank/transfer"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	Transfer.Log struct
//
//	Every time a Transfer entity is modified, a corresponding transfer.Log
//	is generated for the entity. This log is never generated by the
//	user.
//
//	Attributes (return-only):
//	- Id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- Payment [Transfer struct]: Transfer entity to which the log refers to.
//	- Errors [slice of strings]: slice of errors linked to this Transfer event.
//	- Type [string]: type of the Transfer event which triggered the log creation. ex: "processing" or "success"
//	- Created [time.Time]: creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id       string            `json:",omitempty"`
	Transfer Transfer.Transfer `json:",omitempty"`
	Errors   []string          `json:",omitempty"`
	Type     string            `json:",omitempty"`
	Created  *time.Time        `json:",omitempty"`
}

var Object Log
var objects []Log
var resource = map[string]string{"name": "TransferLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific Transfer.Log
	//
	//	Receive a single Transfer.Log struct previously created by the Stark Bank API by passing its id
	//
	//	Parameters (required):
	//	- id [string]: struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Transfer.Log struct with updated attributes
	var Object Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &Object)
	if unmarshalError != nil {
		return Object, err
	}
	return Object, err
}

func Query(params map[string]interface{}, user user.User) chan Log {
	//	Retrieve Transfer.Log structs
	//
	//	Receive a channel of Transfer.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: date filter for structs created only after specified date.
	//		- before [string, default nil]: date filter for structs created only before specified date.
	//		- types [slice of strings, default nil]: filter retrieved structs by event types. ex: []string{"processing", "success"}
	//		- transferIds [slice of strings, default nil]: slice of Transfer ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Slice of Transfer.Log objects with updated attributes
	var Object Log
	logs := make(chan Log)
	query := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &Object)
			if err != nil {
				panic(err)
			}
			logs <- Object
		}
		close(logs)
	}()
	return logs
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged Transfer.Log structs
	//
	//	Receive a slice of up to 100 Transfer.Log structs previously created in the Stark Bank API and the cursor to the next page
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: cursor returned on the previous page function call
	//		- limit [int, default 100]: maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: date filter for structs created only after specified date.
	//		- before [string, default nil]: date filter for structs created only before specified date.
	//		- types [slice of strings, default nil]: filter retrieved structs by types. ex: []string{"success", "failed"}
	//		- transferIds [slice of strings, default nil]: slice of Transfer ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Slice of Transfer.Log structs with updated attributes
	//	- cursor to retrieve the next page of Transfer.Log structs
	var objects []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &objects)
	if unmarshalError != nil {
		return objects, cursor, err
	}
	return objects, cursor, err
}
