package log

import (
	"encoding/json"
	BrcodePayment "github.com/starkbank/sdk-go/starkbank/brcodepayment"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	BrcodePayment.Log struct
//
//	Every time a BrcodePayment entity is modified, a corresponding brcodepayment.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the BrcodePayment.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Payment [BrcodePayment struct]: BrcodePayment entity to which the log refers to.
//	- Errors [slice of strings]: List of errors linked to this BrcodePayment event.
//	- Type [string]: Type of the BrcodePayment event which triggered the log creation. ex: "success" or "failed"
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string                      `json:",omitempty"`
	Payment BrcodePayment.BrcodePayment `json:",omitempty"`
	Errors  []string                    `json:",omitempty"`
	Type    string                      `json:",omitempty"`
	Created *time.Time                  `json:",omitempty"`
}

var resource = map[string]string{"name": "BrcodePaymentLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific BrcodePayment.Log by its id
	//
	//	Receive a single BrcodePayment.Log struct previously created by the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- BrcodePayment.Log struct with updated attributes
	var brCodePaymentLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &brCodePaymentLog)
	if unmarshalError != nil {
		return brCodePaymentLog, err
	}
	return brCodePaymentLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve BrcodePayment.Log structs
	//
	//	Receive a channel of BrcodePayment.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by event types. ex: []string{"processing", "success"}
	//		- paymentIds [slice of strings, default nil]: List of BrcodePayment ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Channel of BrcodePayment.Log structs with updated attributes
	var brCodePaymentLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &brCodePaymentLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- brCodePaymentLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged BrcodePayment.Log structs
	//
	//	Receive a slice of up to 100 BrcodePayment.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter retrieved structs by event types. ex: []string{"processing", "success"}
	//		- paymentIds [slice of strings, default nil]: List of BrcodePayment ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Slice of BrcodePayment.Log structs with updated attributes
	//	- Cursor to retrieve the next page of BrcodePayment.Log structs
	var brCodePaymentLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &brCodePaymentLogs)
	if unmarshalError != nil {
		return brCodePaymentLogs, cursor, err
	}
	return brCodePaymentLogs, cursor, err
}
