package log

import (
	"encoding/json"
	"time"
	MerchantPurchase "github.com/starkbank/sdk-go/starkbank/merchantpurchase"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
)

// MerchantPurchase.Log struct
//
// Every time a MerchantPurchase entity is updated, a corresponding MerchantPurchase.Log
// is generated for the entity. This log is never generated by the
// user, but it can be retrieved to check additional information
// on the MerchantPurchase.
//
// Attributes (return-only):
// - Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
// - Purchase [MerchantPurchase struct]: MerchantPurchase entity to which the log refers to.
// - Errors [slice of strings]: List of errors linked to this MerchantPurchase event
// - Type [string]: Type of the MerchantPurchase event which triggered the log creation. ex: "approved" or "confirmed"
// - Created [time.Time]: Creation datetime for the log.
// - TransactionId [string]: ledger transaction id linked to this log.

type Log struct {
	Id            string                            `json:",omitempty"`
	Purchase      MerchantPurchase.MerchantPurchase `json:",omitempty"`
	Errors        []interface{}                     `json:",omitempty"`
	Type          string                            `json:",omitempty"`
	Created       *time.Time                        `json:",omitempty"`
	TransactionId string                            `json:",omitempty"`
}

var resource = map[string]string{"name": "MerchantPurchaseLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	// Retrieve a specific MerchantPurchase.Log by its id
	//
	// Receive a single MerchantPurchase.Log struct previously created by the Stark Bank API by its id
	//
	// Parameters (required):
	// - id [string]: Struct unique id. ex: "5656565656565656"
	//
	// Parameters (optional):
	// - user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	// Return:
	// - MerchantPurchase.Log struct that corresponds to the given id.
	var purchaseLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &purchaseLog)
	if unmarshalError != nil {
		return purchaseLog, err
	}
	return purchaseLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	// Retrieve MerchantPurchase.Log structs
	//
	// Receive a channel of MerchantPurchase.Log structs previously created in the Stark Bank API
	//
	// Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"approved", "confirmed"}
	//		- purchaseIds [slice of strings, default nil]: List of MerchantPurchase ids to filter Objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	// Return:
	// - Channel of MerchantPurchase.Log structs with updated attributes
	var purchaseLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &purchaseLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- purchaseLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	// Retrieve paged MerchantPurchase.Log structs
	//
	// Receive a slice of up to 100 MerchantPurchase.Log structs previously created in the Stark Bank API and the cursor to the next page.
	// Use this function instead of query if you want to manually page your requests.
	//
	// Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"approved", "confirmed"}
	//		- purchaseIds [slice of strings, default nil]: List of MerchantPurchase ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	// Return:
	// - Slice of MerchantPurchase.Log structs with updated attributes
	// - Cursor to retrieve the next page of MerchantPurchase.Log structs
	var purchaseLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &purchaseLogs)
	if unmarshalError != nil {
		return purchaseLogs, cursor, err
	}
	return purchaseLogs, cursor, err
}
