package log

import (
	"encoding/json"
	"time"
	MerchantInstallment "github.com/starkbank/sdk-go/starkbank/merchantinstallment"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
)

// MerchantInstallment.Log struct
//
// Every time a MerchantInstallment entity is updated, a corresponding MerchantInstallment.Log
// is generated for the entity. This log is never generated by the
// user, but it can be retrieved to check additional information
// on the MerchantInstallment.
//
// Attributes (return-only):
// - Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
// - Installment [MerchantInstallment struct]: MerchantInstallment entity to which the log refers to.
// - Errors [slice of dictionaries]: List of errors linked to this MerchantInstallment event, each with "code" and "message" keys. ex: []interface{}{map[string]interface{}{"code": "invalidCard", "message": "The provided card is invalid"}}
// - Type [string]: Type of the MerchantInstallment event which triggered the log creation.
// - Created [time.Time]: Creation datetime for the log.
// - TransactionId [string]: ledger transaction id linked to this log.

type Log struct {
	Id            string                                  `json:",omitempty"`
	Installment   MerchantInstallment.MerchantInstallment `json:",omitempty"`
	Errors        []interface{}                           `json:",omitempty"`
	Type          string                                  `json:",omitempty"`
	Created       *time.Time                              `json:",omitempty"`
	TransactionId string                                  `json:",omitempty"`
}

var resource = map[string]string{"name": "MerchantInstallmentLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	// Retrieve a specific MerchantInstallment.Log by its id
	//
	// Receive a single MerchantInstallment.Log struct previously created by the Stark Bank API by its id
	//
	// Parameters (required):
	// - id [string]: Struct unique id. ex: "5656565656565656"
	//
	// Parameters (optional):
	// - user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	// Return:
	// - MerchantInstallment.Log struct that corresponds to the given id.
	var installmentLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &installmentLog)
	if unmarshalError != nil {
		return installmentLog, err
	}
	return installmentLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	// Retrieve MerchantInstallment.Log structs
	//
	// Receive a channel of MerchantInstallment.Log structs previously created in the Stark Bank API
	//
	// Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types.
	//		- installmentIds [slice of strings, default nil]: List of MerchantInstallment ids to filter Objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	// Return:
	// - Channel of MerchantInstallment.Log structs with updated attributes
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			var installmentLog Log
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &installmentLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- installmentLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logs)
		close(logsError)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	// Retrieve paged MerchantInstallment.Log structs
	//
	// Receive a slice of up to 100 MerchantInstallment.Log structs previously created in the Stark Bank API and the cursor to the next page.
	// Use this function instead of query if you want to manually page your requests.
	//
	// Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types.
	//		- installmentIds [slice of strings, default nil]: List of MerchantInstallment ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	// Return:
	// - Slice of MerchantInstallment.Log structs with updated attributes
	// - Cursor to retrieve the next page of MerchantInstallment.Log structs
	var installmentLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &installmentLogs)
	if unmarshalError != nil {
		return installmentLogs, cursor, err
	}
	return installmentLogs, cursor, err
}
