package log

import (
	"encoding/json"
	Boleto "github.com/starkbank/sdk-go/starkbank/boleto"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	Boleto.Log struct
//
//	Every time a Boleto entity is updated, a corresponding Boleto.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the Boleto.
//
//	Attributes (return-only):
//	- Id [string]: Unique id returned when the log is created. ex: "5656565656565656"
//	- Boleto [Boleto struct]: Boleto entity to which the log refers to.
//	- Errors [slice of strings]: List of errors linked to this Boleto event
//	- Type [string]: Type of the Boleto event which triggered the log creation. ex: "registered" or "paid"
//	- Created [time.Time]: Creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC),

type Log struct {
	Id      string        `json:",omitempty"`
	Boleto  Boleto.Boleto `json:",omitempty"`
	Errors  []string      `json:",omitempty"`
	Type    string        `json:",omitempty"`
	Created *time.Time    `json:",omitempty"`
}

var resource = map[string]string{"name": "BoletoLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific Boleto.Log by its id
	//
	//	Receive a single Boleto.Log struct previously created by the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: Struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Boleto.Log struct that corresponds to the given id.
	var boletoLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &boletoLog)
	if unmarshalError != nil {
		return boletoLog, err
	}
	return boletoLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve Boleto.Log structs
	//
	//	Receive a channel of Boleto.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: Maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"paid", "registered"}
	//		- boletoIds [slice of strings, default nil]: List of Boleto ids to filter Objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Channel of boleto.Log structs with updated attributes
	var boletoLog Log
	logs := make(chan Log)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &boletoLog)
			if err != nil {
				errorChannel <- Error.UnknownError(err.Error())
				continue
			}
			logs <- boletoLog
		}
		close(logs)
	}()
	return logs, errorChannel
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged Boleto.Log structs
	//
	//	Receive a slice of up to 100 Boleto.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//  - params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: Cursor returned on the previous page function call
	//		- limit [int, default 100]: Maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: Date filter for structs created only after specified date. ex: "2022-11-10"
	//		- before [string, default nil]: Date filter for structs created only before specified date. ex: "2022-11-10"
	//		- types [slice of strings, default nil]: Filter for log event types. ex: []string{"paid", "registered"}
	//		- boletoIds [slice of strings, default nil]: List of Boleto ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Slice of Boleto.Log structs with updated attributes
	//	- Cursor to retrieve the next page of Boleto.Log structs
	var boletoLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &boletoLogs)
	if unmarshalError != nil {
		return boletoLogs, cursor, err
	}
	return boletoLogs, cursor, err
}
