package log

import (
	"encoding/json"
	"github.com/starkbank/sdk-go/starkbank/utils"
	VerifiedAccount "github.com/starkbank/sdk-go/starkbank/verifiedaccount"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	VerifiedAccount.Log struct
//
//	Every time a VerifiedAccount entity is modified, a corresponding VerifiedAccount.Log
//	is generated for the entity. This log is never generated by the user.
//
//	Attributes (return-only):
//	- Id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- Account [VerifiedAccount struct]: VerifiedAccount entity to which the log refers to.
//	- Errors [slice of maps]: list of errors linked to this VerifiedAccount event. ex: []map[string]interface{}{{"code": "keyNotFound", "message": "The key is not registered"}}
//	- Type [string]: type of the VerifiedAccount event which triggered the log creation. ex: "created" or "processing"
//	- Created [time.Time]: creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC)

type Log struct {
	Id      string                          `json:",omitempty"`
	Account VerifiedAccount.VerifiedAccount `json:",omitempty"`
	Errors  []map[string]interface{}        `json:",omitempty"`
	Type    string                          `json:",omitempty"`
	Created *time.Time                      `json:",omitempty"`
}

var resource = map[string]string{"name": "VerifiedAccountLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific VerifiedAccount.Log by its id
	//
	//	Receive a single VerifiedAccount.Log struct previously created by the Stark Bank API by passing its id
	//
	//	Parameters (required):
	//	- id [string]: struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- VerifiedAccount.Log struct that corresponds to the given id.
	var verifiedAccountLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &verifiedAccountLog)
	if unmarshalError != nil {
		return verifiedAccountLog, err
	}
	return verifiedAccountLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve VerifiedAccount.Log structs
	//
	//	Receive a channel of VerifiedAccount.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for structs created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved structs by types. ex: []string{"created", "processing"}
	//		- accountIds [slice of strings, default nil]: slice of VerifiedAccount ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Channel of VerifiedAccount.Log structs with updated attributes
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			var verifiedAccountLog Log
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &verifiedAccountLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- verifiedAccountLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logsError)
		close(logs)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged VerifiedAccount.Log structs
	//
	//	Receive a slice of up to 100 VerifiedAccount.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: cursor returned on the previous page function call
	//		- limit [int, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: date filter for structs created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for structs created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved structs by types. ex: []string{"created", "processing"}
	//		- accountIds [slice of strings, default nil]: slice of VerifiedAccount ids to filter retrieved structs. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Slice of VerifiedAccount.Log structs with updated attributes
	//	- Cursor to retrieve the next page of VerifiedAccount.Log structs
	var verifiedAccountLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &verifiedAccountLogs)
	if unmarshalError != nil {
		return verifiedAccountLogs, cursor, err
	}
	return verifiedAccountLogs, cursor, err
}
