package log

import (
	"encoding/json"
	Split "github.com/starkbank/sdk-go/starkbank/split"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	Split.Log struct
//
//	Every time a Split entity is modified, a corresponding Split.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the Split.
//
//	Attributes (return-only):
//	- Id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- Split [Split struct]: Split entity to which the log refers to.
//	- Errors [slice of strings]: slice of errors linked to this Split event.
//	- Type [string]: type of the Split event which triggered the log creation. ex: "success" or "failed"
//	- Created [time.Time]: creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC)

type Log struct {
	Id      string      `json:",omitempty"`
	Split   Split.Split `json:",omitempty"`
	Errors  []string    `json:",omitempty"`
	Type    string      `json:",omitempty"`
	Created *time.Time  `json:",omitempty"`
}

var resource = map[string]string{"name": "SplitLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific Split.Log by its id
	//
	//	Receive a single Split.Log struct previously created by the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- Split.Log struct that corresponds to the given id.
	var splitLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &splitLog)
	if unmarshalError != nil {
		return splitLog, err
	}
	return splitLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve Split.Logs
	//
	//	Receive a channel of Split.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: date filter for objects created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for objects created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved objects by event types. ex: []string{"processing", "success"}
	//		- splitIds [slice of strings, default nil]: slice of Split ids to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- channel of Split.Log structs with updated attributes
	var splitLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &splitLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- splitLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logsError)
		close(logs)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged Split.Logs
	//
	//	Receive a slice of up to 100 Split.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: cursor returned on the previous page function call
	//		- limit [int, default 100]: maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: date filter for objects created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for objects created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved objects by event types. ex: []string{"processing", "success"}
	//		- splitIds [slice of strings, default nil]: slice of Split ids to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- slice of Split.Log structs with updated attributes
	//	- cursor to retrieve the next page of Split.Log structs
	var splitLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &splitLogs)
	if unmarshalError != nil {
		return splitLogs, cursor, err
	}
	return splitLogs, cursor, err
}
