package log

import (
	"encoding/json"
	SplitReceiver "github.com/starkbank/sdk-go/starkbank/splitreceiver"
	"github.com/starkbank/sdk-go/starkbank/utils"
	Error "github.com/starkinfra/core-go/starkcore/error"
	"github.com/starkinfra/core-go/starkcore/user/user"
	"time"
)

//	SplitReceiver.Log struct
//
//	Every time a SplitReceiver entity is modified, a corresponding SplitReceiver.Log
//	is generated for the entity. This log is never generated by the
//	user, but it can be retrieved to check additional information
//	on the SplitReceiver.
//
//	Attributes (return-only):
//	- Id [string]: unique id returned when the log is created. ex: "5656565656565656"
//	- Receiver [SplitReceiver struct]: SplitReceiver entity to which the log refers to.
//	- Errors [slice of strings]: slice of errors linked to this SplitReceiver event.
//	- Type [string]: type of the SplitReceiver event which triggered the log creation. ex: "success" or "failed"
//	- Created [time.Time]: creation datetime for the log. ex: time.Date(2020, 3, 10, 10, 30, 10, 0, time.UTC)

type Log struct {
	Id       string                      `json:",omitempty"`
	Receiver SplitReceiver.SplitReceiver `json:",omitempty"`
	Errors   []string                    `json:",omitempty"`
	Type     string                      `json:",omitempty"`
	Created  *time.Time                  `json:",omitempty"`
}

var resource = map[string]string{"name": "SplitReceiverLog"}

func Get(id string, user user.User) (Log, Error.StarkErrors) {
	//	Retrieve a specific SplitReceiver.Log by its id
	//
	//	Receive a single SplitReceiver.Log struct previously created by the Stark Bank API by its id
	//
	//	Parameters (required):
	//	- id [string]: struct unique id. ex: "5656565656565656"
	//
	//	Parameters (optional):
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- SplitReceiver.Log struct that corresponds to the given id.
	var splitReceiverLog Log
	get, err := utils.Get(resource, id, nil, user)
	unmarshalError := json.Unmarshal(get, &splitReceiverLog)
	if unmarshalError != nil {
		return splitReceiverLog, err
	}
	return splitReceiverLog, err
}

func Query(params map[string]interface{}, user user.User) (chan Log, chan Error.StarkErrors) {
	//	Retrieve SplitReceiver.Log structs
	//
	//	Receive a channel of SplitReceiver.Log structs previously created in the Stark Bank API
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- limit [int, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
	//		- after [string, default nil]: date filter for objects created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for objects created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved objects by event types. ex: []string{"processing", "success"}
	//		- receiverIds [slice of strings, default nil]: slice of SplitReceiver ids to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- channel of SplitReceiver.Log structs with updated attributes
	var splitReceiverLog Log
	logs := make(chan Log)
	logsError := make(chan Error.StarkErrors)
	query, errorChannel := utils.Query(resource, params, user)
	go func() {
		for content := range query {
			contentByte, _ := json.Marshal(content)
			err := json.Unmarshal(contentByte, &splitReceiverLog)
			if err != nil {
				logsError <- Error.UnknownError(err.Error())
				continue
			}
			logs <- splitReceiverLog
		}
		for err := range errorChannel {
			logsError <- err
		}
		close(logsError)
		close(logs)
	}()
	return logs, logsError
}

func Page(params map[string]interface{}, user user.User) ([]Log, string, Error.StarkErrors) {
	//	Retrieve paged SplitReceiver.Log structs
	//
	//	Receive a slice of up to 100 SplitReceiver.Log structs previously created in the Stark Bank API and the cursor to the next page.
	//	Use this function instead of query if you want to manually page your requests.
	//
	//	Parameters (optional):
	//	- params [map[string]interface{}, default nil]: map of parameters for the query
	//		- cursor [string, default nil]: cursor returned on the previous page function call
	//		- limit [int, default 100]: maximum number of structs to be retrieved. It must be an int between 1 and 100. ex: 50
	//		- after [string, default nil]: date filter for objects created only after specified date. ex: "2020-03-10"
	//		- before [string, default nil]: date filter for objects created only before specified date. ex: "2020-03-10"
	//		- types [slice of strings, default nil]: filter retrieved objects by event types. ex: []string{"processing", "success"}
	//		- receiverIds [slice of strings, default nil]: slice of SplitReceiver ids to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
	//	- user [Organization/Project struct, default nil]: Organization or Project struct. Not necessary if starkbank.User was set before function call
	//
	//	Return:
	//	- slice of SplitReceiver.Log structs with updated attributes
	//	- cursor to retrieve the next page of SplitReceiver.Log structs
	var splitReceiverLogs []Log
	page, cursor, err := utils.Page(resource, params, user)
	unmarshalError := json.Unmarshal(page, &splitReceiverLogs)
	if unmarshalError != nil {
		return splitReceiverLogs, cursor, err
	}
	return splitReceiverLogs, cursor, err
}
